<?php

namespace Plugin\StripePayment\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StripePaymentConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StripePaymentConfigRepository extends EntityRepository
{
}
